config/routes.rb
Twitter::Application.routes.draw do

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

match 'search' => 'home#search', :as => :search

  resources :sessions

  resources :users
  resources :tweets

  match '/:username/toggle_follow' => 'home#toggle_follow', :as => "toggle_follow"
  match '/:username/toggle_follow_via_ajax' => 'home#toggle_follow_via_ajax', :as => "toggle_follow_via_ajax"

  match '/remove_friend/:username' => 'home#remove_friend', :as => "remove_friend"
  match '/add_friend/:username' => 'home#add_friend', :as => "add_friend"

  match '/following' => 'home#following', :as => "following"
  match '/followers' => 'home#followers', :as => "followers"

  match '/:username' => 'home#show', :as => "user_tweet_path"

  root :to => "home#index"

end

app/views/includes/_side_contents.html.erb
<div id="my_info_container" xmlns="http://www.w3.org/1999/html">
<%= image_tag current_user.gravatar_url(:size => 32) %>  <br>
  <div class="contents"><span class="my_user"><%= link_to current_user.username, current_user.username  %></span><br>
    <span class="my_profile">View My Profile Page</span>


    <div class="following_followers_container">
<span class="my_tweets"><span class="hard_count"><%= current_user.tweets.count %></span> Tweets</span><br><span class="my_tweets">
<% link1 = '<span class="hard_count">' + current_user.friendships.count.to_s + '</span>' + ' Following'%> <%= link_to link1.html_safe, following_path %></span>
     <% follower_count = '<span class="hard_count">' + (current_user.friends_of.count).to_s + '</span>'%>
      <% if current_user.friends_of.count != 0 %>
          <% textlink = follower_count + ' ' +  pluralize_without_count(current_user.friends_of.count, "Follower")%>
          <%= link_to textlink.html_safe, followers_path %>
     <% end %>
      </span>
    </div>
    </div>




</div>

<div id="thumbnail_container">
      <h4>Following</h4><span class="following_avatars">
      <% current_user.friends.each do |friend| %>
          <a href="<%=friend.username%>" class="sidefollowing_<%=friend.username%>"><%=image_tag friend.gravatar_url(:size=>30), :alt => friend.username, :title =>friend.username %></a>
      <% end %>
      </span>

  <h4>Followers</h4>
     <span class="follower_avatars">
  <% current_user.friends_of.each do |friend| %>

        <a href="<%=friend.username%>" class="sidefollower_"><%= image_tag friend.gravatar_url(:size => 30), :alt=>friend.username, :title=> friend.username %></a>
      <% end %>
         </span>


</div>