config/routes.rb
Twitter::Application.routes.draw do

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

match 'search' => 'home#search', :as => :search

  resources :sessions

  resources :users
  resources :tweets

  match '/:username/toggle_follow' => 'home#toggle_follow', :as => "toggle_follow"
  match '/:username/toggle_follow_via_ajax' => 'home#toggle_follow_via_ajax', :as => "toggle_follow_via_ajax"

  match '/remove_friend/:username' => 'home#remove_friend', :as => "remove_friend"
  match '/add_friend/:username' => 'home#add_friend', :as => "add_friend"

  match '/following' => 'home#following', :as => "following"
  match '/followers' => 'home#followers', :as => "followers"

  match '/:username' => 'home#show', :as => "user_tweet_path"

  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :login_required

  def index

    @tweets = current_user.all_tweets

    @last_tweet = current_user.tweets.last
  end

  def show

   @user = User.find_by_username(params[:username])
    @tweets = @user.all_tweets

  end

  def toggle_follow
    @user = User.find_by_username(params[:username])
    if current_user.is_friend? @user
      flash[:notice] = "You are no longer following #{@user.username}"
      current_user.remove_friend(@user)
    else
      current_user.add_friend(@user)
      flash[:notice] = "You are now following #{@user.username}"
    end
    redirect_to user_tweet_path_path



  end
  def toggle_follow_via_ajax
    user = User.find_by_username(params[:username])
    if current_user.is_friend? user
      current_user.remove_friend(user)
    else
      current_user.add_friend(user)
    end
    render :text => user.username



  end

  def following
    @friends = current_user.friends
  end

  def followers
    @followers = current_user.friends_of
  end

  def add_friend
    @user = User.find_by_username(params[:username])
      current_user.add_friend(@user)
      flash[:notice] = "You are now following #{@user.username}"
    end

  def search
    @q = params[:q]
    if @q == ""          #hack incase the user enters a blank field!  sorry.
      @q = " "
    end
    @friends = User.find_by_search_query(@q)

  end



  def remove_friend
    friend = User.find_by_username(params[:username])
      if friend
        flash[:notice] = "You are no longer following #{friend.username}"
        current_user.remove_friend(friend)
        render :text => friend.username
      else
        render :text =>'none'
      end
  end



end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_tweet.html.erb
<span class="time_ago"><%= distance_of_time_in_words_to_now(friend.tweets.last.created_at) %> ago</span>
<div class="clear"></div>
<span class="message"> <% status = h friend.tweets.last.message %> <%=status_parser(status) %></span>
<div class="tweet_footer">
                <span class="expand-stream">
                    <span class="expand"><a href="#">expand</a></span>
                    <span class="collapse"><a href="#">collapse</a></span>
                    </span>
                <span class="actions">
                    <span class="reply"><a href="#">reply</a></span>
                    <span class="retweet"><a href="#">Retweet</a></span>
                    <span class="favorite"><a href="#">Favorite</a></span>
                 </span>
</div>

app/views/home/_tweets_list.erb
</p>
<ul id="tweet_list">


  <% tweets.each do |tweet|%>
      <li<% if (@tweets.first == tweet) %> class="first" <% end %>>

        <%= image_tag tweet.user.gravatar_url(:size => 48)%>
        <div class="tweet_message_container">
          <span class="full_name"><%= link_to tweet.user.username, tweet.user.username %></span>
          <span class="tweet_name"><s>@</s><%= tweet.user.username %></span>
          <% if tweet.message %>
              <span class="time_ago"><%= distance_of_time_in_words_to_now(tweet.created_at) %> ago</span>
              <div class="clear"></div>

              <span class="message">
              <% text = h tweet.message %>
              <%=status_parser(text) %>

             </span>
         <% end %>

          <div class="tweet_footer">
                <span class="expand-stream">
                <span class="expand"><a href="#">expand</a></span>
                <span class="collapse"><a href="#">collapse</a></span>
                </span>
                <span class="actions">
                <span class="reply"><a href="#">reply</a></span>
                <span class="retweet"><a href="#">Retweet</a></span>
                <span class="favorite"><a href="#">Favorite</a></span>
                 </span>
          </div>
        </div>
        <div class="clear"></div>

      </li>
  <% end %>
</ul>

app/views/home/followers.html.erb
<div id="notice"></div>
<div class="your-following"><h3>You are being followed by <%=current_user.friends_of.count %> people.</h3></div>
<ul id="tweet_list">
           <% @followers = current_user.friends_of %>
  <% @followers.each do |friend| %>
      <li<% if (@followers.first == friend) %> class="first" <% end %> id="<%=friend.username%>">

        <%= image_tag friend.gravatar_url(:size => 48)%>
        <div class="tweet_message_container">
          <span class="full_name"><%= link_to friend.username, friend.username %></span>
          <span class="tweet_name"><s>@</s>username</span>
          <% if friend.tweets.last %>
              <%=  render :partial => "tweet", :locals => { :friend => friend } %>
          <% end %>


        </div>
        <div class="button-container">
          <% if current_user.is_friend? friend %>
        <%= submit_tag "Unfollow", :class => "follow-button", :name => friend.username, :id=>"unfollow" %>
          <% else %>
              <%= submit_tag "Follow", :class => "follow-button", :name => friend.username, :id=>"follow" %>
          <% end %>


        </div>
        <div class="clear"></div>


      </li>  <% end %>

</ul>

<script type = "text/javascript">

    $(function(){
        $('.follow-button').click(function(){



            if ($(this).attr('id') == 'follow')
            {
                var followname = $(this).attr('name');

                if ($(this).css('display') != 'none')
                {        alert(followname);
                    var appendhyperlink = $('<a>').attr('href', followname).addClass('sidefollowing_'+followname);
                    var appendimage = $('<img>').attr({
                        src: 'https://secure.gravatar.com/avatar/ba84dd7085d89c6eabadab643749b177.png?r=PG&s=30',
                        title: followname
                    });
                    appendhyperlink.wrapInner(appendimage);
                    var areatoappend = $('.following_avatars');
                    $('.following_avatars').append(appendhyperlink);
                }
                else
                {       alert(followname);
                    followname.show();
                }
                $(this).attr('value', 'Unfollow');
                $(this).attr('id', "unfollow");
                $.ajax({
                    type:'POST',
                    url: "/add_friend/" + $(this).attr('name'),
                    success: function(msg) {
                        $('#notice').html('You are now following ' + msg);
                         $('#notice').show();


                    }
                })
            }
            else if ($(this).attr('id') == 'unfollow')
            {
                $(this).attr('value', 'Follow');
                var follower = $(this).attr('name');

                var sidecontent = $('.sidefollowing_'+follower);
                sidecontent.hide();
                $(this).attr('id', 'follow');
                $.ajax({
                type:'POST',
                url: "/remove_friend/" + $(this).attr('name'),
                success: function(msg) {

                    $('#notice').html('You are no longer following ' + msg);
                    $('#notice').show();

                }
                });
        }
        })
    });

</script>

app/views/home/following.html.erb
<div id="notice"></div>
<div class="your-following"><h3>You are following <%=current_user.friends.count %> people.</h3></div>
<ul id="tweet_list">

  <% @friends.each do |friend| %>
      <li<% if (@friends.first == friend) %> class="first" <% end %> id="<%=friend.username%>">

        <%= image_tag friend.gravatar_url(:size => 48)%>
        <div class="tweet_message_container">
          <span class="full_name"><%= link_to friend.username, friend.username %></span>
          <span class="tweet_name"><s>@</s>username</span>
          <% if friend.tweets.last %>
              <%=  render :partial => "tweet", :locals => { :friend => friend } %>
           <% end %>
        </div>
        <div class="button-container">
          <%= submit_tag "Unfollow", :class => "follow-button", :name => friend.username%>
        </div>
        <div class="clear"></div>


      </li>  <% end %>

</ul>

<script type = "text/javascript">

  $(function(){
     $('.follow-button').click(function(){
              $.ajax({
                  type:'POST',
                  url: "/remove_friend/" + $(this).attr('name'),
                  success: function(msg) {
                      $('#' + msg).slideUp('slow');
                      $('#notice').html('You are no longer following ' + msg);
                      $('#notice').show();                  }
              });
     })
  });

</script>

app/views/home/index.html.erb
<script type="text/javascript">

  $(function(){
  $('.tweet_message_box').keydown(function() {
          var content_length = $(this).val().length;
          var remaining = 140 - content_length;
      $('.timer').html(remaining);
      if (remaining < 55 && remaining >21) {
          $('.timer').addClass('cool-grey');
          $('.timer').removeClass('dark_red');
          $('.timer').removeClass('red');
      }
      else if (remaining < 21 && remaining >0) {
          $('.timer').addClass('dark_red');
          $('.timer').removeClass('red');
          $('.timer').removeClass('cool-grey');


      }
      else if (remaining <=0 )
      {
          $('.timer').addClass('red');
          $('.timer').removeClass('dark_red');
          $('.timer').removeClass('cool-grey');

      }
      else
      {
          $('.timer').removeClass('dark_red');
          $('.timer').removeClass('red');
          $('.timer').removeClass('cool-grey');

      }
      })
  })

</script>



<%= form_for Tweet.new do |f| %>
    <div id="new_tweet_form">
      <h2>What are you doing?</h2>
      <span class="timer">140</span>
    <%= f.text_area :message, :class => "tweet_message_box"%>
    <% if @last_tweet %>
          <div id="lastest_message">
            <div class="status">
              <% if @last_tweet.message %>
                  <strong>Latest:  </strong><%= h @last_tweet.message %> <span class="status_time"><%= distance_of_time_in_words_to_now(@last_tweet.created_at) %> ago</span>
              <%end %>
            </div>
          </div>
          <% end %>

      <div class="tweet_button">


    <%= f.submit "Post", :class  => "tweet_button_btn"%>
      </div>
      <div class="clear"></div>

    </div>
    <div class="clear"></div>


    <%=  render :partial => "tweets_list", :locals => { :tweets => @tweets } %>



<% end %>

app/views/home/search.html.erb
<div id="notice"></div>
<div class="your-following"><h3>Your search returned <%=@friends.count %> people.</h3></div>
<ul id="tweet_list">

  <% @friends.each do |friend| %>
      <li<% if (@friends.first == friend) %> class="first" <% end %> id="<%=friend.username%>">

        <%= image_tag friend.gravatar_url(:size => 48)%>
        <div class="tweet_message_container">
          <span class="full_name"><%= link_to friend.username, friend.username %></span>
          <span class="tweet_name"><s>@</s>username</span>
         <% if (friend.tweets.last)  %>
          <span class="time_ago"><%= distance_of_time_in_words_to_now(friend.tweets.last.created_at) %> ago</span>
          <div class="clear"></div>

          <span class="message"> <% status = h friend.tweets.last.message %> <%=status_parser(status) %></span>
          <div class="tweet_footer">
                <span class="expand-stream">
                <span class="expand"><a href="#">expand</a></span>
                <span class="collapse"><a href="#">collapse</a></span>
                </span>
                <span class="actions">
                <span class="reply"><a href="#">reply</a></span>
                <span class="retweet"><a href="#">Retweet</a></span>
                <span class="favorite"><a href="#">Favorite</a></span>
                 </span>
          </div>
          <% end %>

        </div>
        <div class="button-container">

          <input type="button" name="<%= friend.username %>" class="follow-button" id="btn_<%= friend.username %>" value="<% if current_user.is_friend? friend %>Unfollow<% else %>Follow<% end %>"/>

        </div>
        <div class="clear"></div>


      </li>  <% end %>

</ul>

<script type = "text/javascript">

    $(function(){
        $('.follow-button').click(function(){
            $.ajax({
                type:"POST",
                url: "/" + $(this).attr('name') + "/toggle_follow_via_ajax",
                success: function(msg) {
                    elm = $('#btn_' + msg);
                    if (elm.val() == "Unfollow")
                        elm.val("Follow");
                    else
                        elm.val("Unfollow");
                }
            });
        })
    });

</script>

app/views/home/show.html.erb
<div id="following_user"> <h1><%= image_tag @user.gravatar_url(:size => 75)%>
<span class="current_user"><%= @user.username %></span></h1></div>

<% if current_user.username != @user.username %>

    <div class="follow_form"><%= form_tag toggle_follow_path do %>



    <% if current_user.is_friend? @user %>
        <%= submit_tag "Unfollow", :class => "follow-button" %>
    <% else %>
        <%= submit_tag "Follow", :class => "follow-button" %>
     <% end %>



<% end %>
  </div>

<% end %>
<%=  render :partial => 'tweets_list', :locals => {:tweets => @tweets} %>