config/routes.rb
Twitter::Application.routes.draw do

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

match 'search' => 'home#search', :as => :search

  resources :sessions

  resources :users
  resources :tweets

  match '/:username/toggle_follow' => 'home#toggle_follow', :as => "toggle_follow"
  match '/:username/toggle_follow_via_ajax' => 'home#toggle_follow_via_ajax', :as => "toggle_follow_via_ajax"

  match '/remove_friend/:username' => 'home#remove_friend', :as => "remove_friend"
  match '/add_friend/:username' => 'home#add_friend', :as => "add_friend"

  match '/following' => 'home#following', :as => "following"
  match '/followers' => 'home#followers', :as => "followers"

  match '/:username' => 'home#show', :as => "user_tweet_path"

  root :to => "home#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div id="header">
        <%= image_tag( "twitter-logo-small.png", :alt => 'logo') %>

      <nav>
        <div id="nav">
          <ul>
            <li><%= link_to "Home",  root_path  %></a></li>
            <li><a href="#">Connect</a></li>
            <li><a href="#">Discover</a></li>
            <li><a href="#">Me</a></li>
          </ul>
        </div>
      </nav>


        <div id="search_bar">
          <%= form_tag "search", :class=>"search-form" do %>

            <%=  text_field_tag :q, @q, :class=>"search-input" %>
            <!--<input class="search-input">-->


            <span class="search-icon" id="search-click"></span>

        <% end %>

        </div>

      <div class="logout-box">
        <% if current_user %>
            Logged in as <%= current_user.username %> |
            <%= link_to "logout",  logout_path  %></a>
        <% else %>
            <%= link_to "Login",  login_path  %></a>

      <% end %>
            </div>
      </div>
    </header>
    <div class="clear"></div>
    <div id="container">
      <div id="main">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>

      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
      </div>
      <% if current_user %>
      <div id="side">
        <%= render :partial => "/includes/side_contents" %>
      </div>
          <% end %>
      <div class="clear"></div>
    </div>
  </body>
</html>